const POPULATE_USER = "LOGIN_USER"
const LOGOUT_USER = "LOGOUT_USER"
const LOADING = "LOADING"
const LOADING_COMPLETE = "LOADING_COMPLETE"
const ADD_BUSINESS = "ADD_BUSINESS"
const POPULATE_BUSINESSES = "POPULATE_BUSINESSES"

export {
    POPULATE_USER,
    LOGOUT_USER, 
    LOADING,
    LOADING_COMPLETE,
    ADD_BUSINESS,
    POPULATE_BUSINESSES
}